---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasigo-db-superuser
  namespace: database
spec:
  encryptedData:
    password: AgCtSa69jeGraaztXUic9nU2aE7gwREoY4yEEqN1c/bZEXMcvslJGcTTmjvtQwVBBBKB7l9LuymlNJiu9i9ZtFJVxzdZVrkChNVSDfomFPQEVztCkqn0F9Je7xsfCemCAzSEQa0N3AGtWlNEss9kLss7zSPeyTGM/lQPnTaWwso40diAneMmARDAyvr14QuPysCf9aH0zFsUY+S6U4p9+n26q65Fmu3rjIP6r2kjVOeOJQlYVTPVXGGsafnGmXdGharkWbb9E1RQWPCiyLTxuwxVbo9OOgWo0Vt4iV/Ro3xxVMGUq7lrA5dvinawCmVGh94s7/85anW7oFksfaSa88tJ8LHf0lErpXM2ur96ve3S992WOBvUJcCMQMCSLg36LT4vFCMXa6tOcjhzwdsJJPurgix1ZtBCtCBm2UlFRQdm81zCrnYMV2ys7ejgGY2OU9QQG94ruS4KDIqFK6TalTmXtzbmJ/Xke52I+9GsM1x1eLLVPRrRpPjhn2l/bvxhuw7w80TF34FbDJDOJxliEENav2qon9hWlaAM8ZR8oQClMI8Kbh5CllNJxfnx4iNFkC2W2CSujDw4gcX+2QXIWuibSl8PTGfslBV6ZxlSHgpiU1IFFlUeRglpUxavgQ3xmXCMB7dGE8x6J51KhkvO0NBSLxBVHUJ9O43NzcfwvLy9Nnx2iBXgUjQ3e6WQlQtM7EJe0NhjxZ+0JWYLbHkHIK3VhtCC1WYYa7aDcQU=
    username: AgAodRcbeu/24JQ7ghFkZPDGqzR8bYEN1zxU++umBxPLpGBFzJwzQjzH7QbvIAMk8B/NpvNAA8PzLlAlTMq8d2ZJMpE74LAwuFA/UZiwnwYO1fYozZcG6rI4bm5o35qb6odrOd8RDGVzsMv4SDQxBRWKRhkYE0axocRJcWlU72WSF3I27Wc/Fr4BkCybK3rhH9uqPFwsGpbr6xzY7erigfKn6zmjXDR1guLR5rv0Tfe+lUyqfhVN4LxZM2fNMvpu9ALKpy5cN8ld7twYGZkTRzdMFzVEOp75oKvJxkXcxjhOtqCmo2sRPdWtVuzSnWp54QULtXykH2zsI4kUGpYMTrH8VNf4uYY//Ph/ht6/81E8GIZA62icD6LepUve6GdfdZHnJvRe9SXTUFLtYf0OJpNkQLP/wDb+BcMluFdJ9HOIPdkgJUaZQTT7wvs6rAUwz+fYxaODMID//j6UNnt3bAzqc7NsD01E0bbJTwuEY//1A0rICAY3lEXLlTXWCp7kpFMWrHO1NWJ+nQTAdS5uiDggMua8o0868/7PUf4UVof7suIR3QlhNoDyYKDOku2ekA+ojHoPhjLomfnRNwGTsiEYiEPGUeLTUykyhWa7cmmMhsFexFAhVxDVlKY/aa+tNFlNzhFxDHUnTNwUd2o47hl2XvY3ZjwwYlsZsiJBzEiIUVJkT+T0f0zot43nucYkRLsALA/DN0Kncw==
  template:
    metadata:
      name: wasigo-db-superuser
      namespace: database
    type: kubernetes.io/basic-auth
