---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasigo-db-app-user
  namespace: database
spec:
  encryptedData:
    password: AgDWbXuJonNXD1OobetTXLZYuuN34W0aOUX3PdgzFhLGwW8wPRICz16JLOdZllKCencqglmgXhNgLgD37H7xwJuo3otJce6qwckWEIYU+3d/HLQGgF81Gebn6uCFrVW3GKlVqvYpxbMFBlG8w0pSrpQ429IdyOYhuScbCSAMVyKXIs9zALTBwDGH3FELCjp0tcCQBNM2SmDVCMhI3OHU1W8d24jLuY+D/gancCxA+ERNbrQHg6KU3x3QngU3c/TZ2kVnZ84kgxPs2mrHxwQoOfIdr4aq0CbkUwpsioq2oDnkImlxbOFZ22sJQPzHAqALMw+GguvzXCATZ7sxbmmYsPKFWjsH3RMF/Z90FD8iyo8VN35rHsiXPIGtYAl+6GMpz7bso/CwXliNLKweInQ68YHEmFjC332ioDbwCvR+lhWfMr4MIlnEqniHXIttN95BkzxITNi4Fzp+noW24mmMqB5fycq2/aXEGSvpQrKHC/98blKT7b8HDTTcWSxi+WVZCnJQrXDhhLgKtK1Gtx8XzufU8gE1EBoCdArIyKGYccQp66D0QQhKfuneCphculd8lQMxfv/O0Kx3NrWjk4FVa8Q2mJfzEv3xab/T+Yezxgqfm4/5d/lid5YRJNPnkXAHFJ3S2dIbAOXSGNsjJjXc7EjtW7/3nx3eRZCpB8DplzwEVMqBpWNIaB5CNAUV+QZ47V2Hi6K+fKcgQF5Y8UOc4A==
    username: AgBkLKxJnH8sp0he8CUMtw/wpeNPTQRDvmgGo88zKy+ydE/ZJE5dnGG56Da/8+UGce1Be/j7OO9EWL47Euvs4NmRhDznqiw13eWsSAsy4J3yIt+G2rogpfUH36u8xTDG6Y6iQJLIWhTp8rONh8IwrDlmili3lr76lWgAWcT+MEEonPyra+5gDRR6/fdcbhSI/gEnrdRZWJROcYKt87IaFN6HDWJ9zQT2bz6yUCoiHw2w1bj2suSHfx4B5GSz9qIwzH9RMyK7oK+y+/uXuMbDH5Hgz4ZY9za/xgQBE4n+5Oj9wPnA9r+CzlVvLzFwguyS9vra5QlI2+wlOGukXrWspCVESQGNtIeNjFrL3PsFyABfPJcKvq3PIZtdemMFL7pc0Ko8fNamxYK3XB1WH+OnmNq5+jOr0wR3hjGvijzClrnXi6dpstwBlMuFIXqwMMqRUUTVOXhDXm1dUHeAVN+c+6M+RSwFjt1A4ndvpzbE3RaywSqxfJFU0PVzxTM7b2l5YvK/+s2PziAu2fvQy2GN5Em0rtHtrPZnSKUM4WRwwRfB8we2wcvJ5Z1nRS93ydy3GF9dpwZ+qn5PSPxZs39U9g7WXW+Mculx6QveMFfGk6G5FtdI7x22lpIRiK1qB4LbXME7dBPlXAyTcidOYOp0U1vTjnlleLhWH4uaquiYhF6x7fIZu3oB6FOkxUXrSycgaFBc0ShvAM5LByKI
  template:
    metadata:
      name: wasigo-db-app-user
      namespace: database
    type: kubernetes.io/basic-auth
