---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasigo-db-migrator-user
  namespace: database
spec:
  encryptedData:
    password: AgA8MrUpHeERBD7aNbirY+zhUF2aSXscc0YhS/B3xTIywaN14MQtmkJYNl28vwJWcUkMAkh9ubF+SkvT0vJ4SeC8StEm9LWYomNXN9/7tqvThw24C0eso/v7fvJ5GYpSUc6gFHNK1tlNyF+UtTy3O779XMIiV89FrqEGFFZktEX2PJ6LzthdLxBXoP/EDrbxbnhtqfgOBWTBNu9lt3BQQfJSgx0q/YTWrJlsKxJEtOsneNmlu6YBTFf0amAnTpj7cLJZDbrQRDCEO9hevrCuPIQE6aAGsbITmcW5ku6XtbnC6Owt5Zri87l/IebIPW8ZsgWKd/jG7Qz3Y7NCI3aZshZbHb3RXx54IZlBSj9fbq5ZO+kwiGgtSQ8DaaRPUhNs7rvMGjzDp9xjSSj57vPCUyvvbOIvxAKHBuqCLCMsFrXbzot8Py+Ejq7RLSoasddu8qMQ8lZ3lMTLQo2TbgE/quJGVtsFcfKeOcnveREDdN7sbnq3pI8uJmkQ+OdDVo0Ez/RTFY3cChqJj6CZ1akf9wj4a5c3fEqw2lygqIB6lDo5m9DGOd9FTaa4EwT4BDqaCJPXFrferDghBnBQ/tyG155aqvlTZRHqaWrpt2Z9hwms03uHzut3og1AKxht8a3umX/j5h/LttLHkNDeRQILm2meTjzBE9mGwsB9eRb0J94St+legtLsc6LZ7fv3QwyUFSsPl3A+vpBtDDApYzSIaPT6QOQF
    username: AgBGXtx/+EK0eu3j2b8cz4TFyQtWEsEISSXQg+eDx1vjkBH5PFqcdWH1CDprbs+cMVNwe8YXuMAPL2/HhMhfn1yqRjsSiR6T7CfOdg9NF279yFNLTdI0oTn/MkVrePdM54j7wNJcMqHRUgHuKP7NdanmmCfK10JlD5YtAq9XP+5r5MirMzLHwXIsfxp4S7laDlT8sJUVHmT1mATpS7IH5P+xcy6U9ZttBp0Ty6dUJBjpESj7P3PtQujoKnaxJe9s0sSZTH9JP7g3BGZp++yU0UFl7ylZT/Q5wir1ecNWSMHOx2N2SUVb7jjNqZBZi2DmhLzgVdFsx9YATuJPb0HbV0BcFrulG2YpJWw81xS1ntfjilcw2J8csBk2hY3isyrhzX9H42ykv1oxy9aSd3YctzO0jfhURHEJvZdeMiULU/zesmX5R5ASOojZU0Sk1MLXa0JRPvUsm6zjgvubTPBCLFuoAVmgCjIe7itWJgzFbXPpNTmo9pwN7F5YBmyUQtImKj2cw6DUiFYktGuHWGH+T2CqQboDZ3t+Zyu8zvPJAgvd1x2SZ3Mrei1Ojt3pbTueiQMYOk7Bn7baWLpmCcl89CfpGZN8wFAnZA8KpLGZ1wBgKg7uwXJR/mtFR1xUfxTV+l+wB4qKKF9bIwbVNeNrjz3OMfcXKH1rYgAc75CffeHhwgT1AJYBXGZBySTGhfXOFmqqiybJgb+0aEylTRn9KNY=
  template:
    metadata:
      name: wasigo-db-migrator-user
      namespace: database
    type: kubernetes.io/basic-auth
