---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasigo-db-superuser
  namespace: database
spec:
  encryptedData:
    password: AgAp2vKMJj459GTNSYlgxYn34BLPm2U6//j6Esu4X3e2oPTUgK7tBZzvjok5wfQAtBnBdv8AhpuPA3uMOrfqS3+UqjmO1HgDGW4X1BJ+jma3qHFGRCGePN3XzRLNduS6w3/9sgdAIEJr/RSqN6O4uDKs/DqAhxKNfIFl9J6IffapgDg6RY60mG1fMoS9DvXWiqkPF5haETaM2RtKwVDuodBJbXGrJsGd6U/TmCtUdYubIb/LHt/jTtb2ADkxXlFfCChkymtbnEcGBQEuL/+KobxRkavrMNRGCNTbct0SVVJWZq5jd6xicOeBLyiNQ6bhYeBYrWMk+aqbESMdk6AU4mR3mIT3xa93O1z8O2J0M1pYGhGULDtwXVaQIoAeuU8QLi+zx5LACxH34//b8NADZchCRWkPxa0v+nQciyLQYw+Oy39cQGYmApnUNOa0W1j+WdrRUDf3ECfUobdki7dZYmOOksE5oH0t47fSBFa7WA/DzggIWhH+Vw4LcyCW/oC0P0RfSJdPK3UGnZeKQ7XuTS/zmHz/eY3edeCyK+ljWfPxxEKlPXKQmjmwqfxZMrT8eU3f5jRLabelXZfN4iPD+DnibX2tSybXkJ4sfNFLsc3/Zo27d3U2pkx7QOMXkLAXSAuLGVv+YP7AlZ1d+yPxoqDak8rDwuvCuXBW07/y6P4/xVXFUrzk02XpmRg1yvMnqDW0hw6chHAEdb9JuwOa5JyAQz6xSpJ4tYPFET8=
    username: AgCj3Qtd6bob+DzEioFiU+b6lU1gkOt/nUphEf4o3yhp7DLYChjh7xsT6pE8CfhZ8iu+JNeh2nUgVmTiyP8y3lzLcxxixuIzNKTF9WNh+azhKo7hZkMrfTVwLEruybjZAUUnJWFVAGtRGjiKnR7WW9ze5rzI7cdJ8m2DAVSmYAatKX1rJq0paD2gjwkY+hF5sFy2d+V4yekqp6sB6bO9DBjBNK7DPzM50NQ9A/lMx8vYTSiEEkNDW0OtrF9SG5wdPRFNZQIWFsVZ9KueJJO0Hc3WaDe/fU9NgqNd5RLPDBiN8vg8C0J89tswY+nTv7ONE3rNn635rXZ8ZR1pEXeAxx2VdAUO8EuulnSBr/ZyEyu0clkrkcTA1j1En5b/aHNLaDOs5o2LBc5wLn/0ds0nDBs36A5o9vMwNUv4fQrPd5NPYHLzq4a3PdlQH7Nq7zk3byWFttYSzASTnxy6zx+aMOUEtII9QvcTjp82kRsQTvtlKPP5hdrncPsqRRZdbtjfntzHqSJAfWD6uXd5xteRliz+BSr7epte2mWcUCxe+kiobCaUcv80O+qdka8RZRlZKdcTgqDNQDa+fu5+y8DuEw7F/m0zg76Dwpm+lYrqC4kuX8HTP2d7CtUwDYOon/ERHRnVuX7RjXXRdwkQW4aOtyLQKQF99cYc7kprgwC/bDLkM0AIDwdW974Ih5rOgW/lWoPDRhTAaKwX8Q==
  template:
    metadata:
      name: wasigo-db-superuser
      namespace: database
    type: kubernetes.io/basic-auth
