---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasigo-db-migrator-user
  namespace: database
spec:
  encryptedData:
    password: AgB+jag2A6KNfo0MoL6dHEHilG/CtHuhv1JsSukGofwsic9K9AyHU/Lc007JHw2V/ZYGnD5vjuRlIHPFKj5CNDMgeyPdl3dM1sWkRh7tpsLD3gPoXE+Xrc3U/y7jXkWz5gzgqm1qwQOfpxej2L/k/kcxsWLo5dNTxftiM/ahy7htoIRKhf8xpkyZ5nyoROwzfNAi3UWoCzp27BNbQhBaLIj5MNrEaQ85c36q1dl5BPs3RoO4COMlUgEKw/z57Mh3cpNY6P2iPSeG5KixT/jpkUzSEkPWdUMBaHy33bgUFAk38KpzsDpyXGM6Yv/xgx94G8Jh57SLjGgeg8LxP04+FX3wGCJlOjnLpsU61YmCUllXJ5w2g8ojRCPtAa5PLhtaHJXLGoS5kiVFpKGqkhdIUIFA8LcHPMxh2mVl0ipUeR1sVcrw8uBvIj77+eSxcpXUkuxdLseQ5bg+VEWixKGYYMLLWsirdJJqoA2I4ftn6s8Af/Pv/XMOjz3p+kIQPbjSvzWtRZlS2ln08J/JzR9DIzA4D2SaONyEdYy0XIe7M68VP5Wj5EwqZAgDok1iLGDo10vSf6xADnL7W2cKr9UsTnMrYFR6NBr/SXujtY7WG3C2BMJ7u4lWJ1+zAY4yP0r2vzMG7Igz+WvFJHlFlkIuhr3OQs6x3ej9q/QbbyarWFEYHxuwLM3utr53B+MMk66jAdKL+YU5Tj55Na3touvElhTTusVA
    username: AgBe+0Lv8NcBYsnmfsleYfITSuQcotX9Bf2YRuAsXUrTPpQApQns64DgwynFfjGLtMu83Ezg/kwGx6oRKT+wyRIRgD/ate+vyv2qs84BAsFOwVOJXo2MWZ6oBah0vKv3m3GccLmTxd6NYMwj3nXVSVXbNfenbIZoHmTpgzIe1RJYMqeBpQN3RQVspRnBQeKTFKHJHjDmjLK0b4bGIPa2AL+ro0ua/S72g03JbhIX8JoZ4C3+gKsRrpikWlRIHHKNkiCsJ8Xo3ZSPq9p02QiqH7M3tC5v0yENgzxTLhwSlfe/zG5UcYLSPXPbr44sa5OKN5HGK5A7ukdXr7Eqh7KPBnfHevX6pUoi4OrgmHt4h8R2awhq+u2xsDvgtw5YA+HTh1dDWPLoBs+yiAaLe5oFFcU87LSD2CVntbwzv8lFhfGy0XNOIMYtWj2G3mCTuu9LCIb5qdT0t6yCBa7/6yqIJV2imZhaMaKERak3yQDzYB/AAGdW/TmTNzM316Y8bJ0J1RPPWSDiUb8FiIgrn2LHk8LJPI1s+NNEsrUdjU0mxnecsB4GGcdgACgUhISmm1+Wz2Iw2vU5lXpNBbiWuHaIKx1FPy4F7Yoj4MC718yiBVPsvqHlKSORLYHnr/uyf9Hp/JWxv4UA/YMopbtAInIww570s9YOEH8oh4LfA3WX1vSUtag3zm7resMAD1Z+DHJl1sSY/erD2DUE9yQ9lVVf0A8=
  template:
    metadata:
      name: wasigo-db-migrator-user
      namespace: database
    type: kubernetes.io/basic-auth
