---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wasigo-db-app-user
  namespace: database
spec:
  encryptedData:
    password: AgBx5O5Hq8EIHBcpr+uKqzlUz6qLZNxiZ5eQP7itz+xBBmrAZww6h4lRWmwhAO+mw8gAKg3j7wpC3fuK2FfEo5vi08mbm1JYsAB2m4XiIlqmNCFDhj01kAq4YdPgyiejFpZs3fnJewkRLc0o6+DPI8o5vdWrGQDo44v3I4K5troKN2Q3C74v0lZzF3STy+Y1ii+b7FF212bZ9/4aCpeNcFcUw/TwWFR1uv8VwFvPGsA6VkJjIOIpUz31L+cdKQy4XxvS6cqQio4CSsH/Npj4sTeJ4XxHP1Hbxxnu2vQ/aFESVzRI9MxY5rUl97E3szUXFQGq+0mnlU+6LcMJGg2OmVCAHPtLOzAOdMvS430z4UhJaxQL4UNk8G1Xm5MDIBN6QUa3gH5wXECDN3qKxwMtzR8Qk+msdsKro9Gj6YHnZQri4pNxXumVmtSWMadLEO+AAtabpfSrfCz4g8HtcyFiW6+rgHNJAwjNRjSJgNbGPC+eEq79bVeOsMCUXhe0tq7OD826p27Y1drKmYCCW47UZ31H56iGhzo5OSZU/7asgYHoEAHd6xktSvLC2mnSd3QBKX/1oI0eQ3er86VceUj8xK0Wc1r8cxUuf7RV7f7NMu72PzqpIL4JDXmw3TKuDK5zDPq0lCf6jBJrDwFPze1aVmcZoqfaZr4RcH48m0Mc84K4MnH9jVZUmCcdlrSKy1d86RKZH6reMWk9CTvEaKo3Sg==
    username: AgAZgH6UhnxG4x2hSYmmi8UaHUTgua77rwgROp9qKrnBKG8HSQ04GQuvMFqdbqtFIYgt8w6bBWUoQdDN2g7VDGggasm/vudS/ikyfjxfMz08XONZfnW6rMpqm/wWjhGyxNiRLwvbGxSVSHLlRYQLclFTaoS28k3KL1XfJADL61hUgM4nXF00I1VdjAOCoP0JDGaEd0bhHm7WS2VWVKY19kerpifVxF6bUj+ommKd7qsXrOX3SKyAY55HkAzgKZawuu6k6y2uHEJsbQfue0Uv4Guq90s+oDeAWB3ze9030zx7EoUvH0lfozyrv5gsgcmr9x0bCUQ+Cx0usZTDBHtafhsxfHo4Qjj+g5npv3KcEheSPCI8qcLNW9zc7DnBc57PHUKJ1Ywos13V/1QezLsfaA5sYcdMWUAifl/jyI0k/tG/OFN4whiGJa5JNvORos22hxVZhm6eBCF8pNL1uEMpmYzluyLCPkX9rVRZ5iGcBMcUr0LF4R8ikD1/JZf5KiM6KteEqfHASbDVwIrD7X/kHwvB7vVBUze6tQmSS7w+/cuqabuJmgLMaBAMO2P4f3KrWdzlCn0mXzAjRJfleOA8SNe/0xMhJJrCFJ4YPYwfY8/2AG9QtvSsEnwey90z+iaAKfNTw5wdBBGJg93dMquA1jZR/yEUIQ1CXnUl1IDsSwvDlzkXUMPn97abvUJBXn/aWcq1macEnA7fQTpc
  template:
    metadata:
      name: wasigo-db-app-user
      namespace: database
    type: kubernetes.io/basic-auth
