apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasigo-backend
  namespace: traefik
  labels:
    app: wasigo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasigo-backend
  template:
    metadata:
      labels:
        app: wasigo-backend
    spec:
      containers:
        - name: backend
          image: docker.io/xolhed3rp/wasigo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - configMapRef:
                name: wasigo-app-config
          env:
            - name: REDIS_HOST
              value: "wasigo-redis"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: DB_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: REDIS_PASSWORD
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: MINIO_ACCESS_KEY
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: MINIO_SECRET_KEY
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: JWT_SECRET
            - name: MAIL_PASS
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: MAIL_PASS
            - name: PAYPAL_SECRET
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: PAYPAL_SECRET
            - name: GOOGLE_MAPS_API_KEY
              valueFrom:
                secretKeyRef:
                  name: wasigo-app-secrets
                  key: GOOGLE_MAPS_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: wasigo-backend
  namespace: traefik
spec:
  selector:
    app: wasigo-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wasigo-backend-ingress
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: api.wasigo.137.131.164.217.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wasigo-backend
                port:
                  number: 3000