apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasigo-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasigo-backend
  template:
    metadata:
      labels:
        app: wasigo-backend
    spec:
      containers:
        - name: wasigo-backend
          image: nginx # Cambiar por la imagen real del backend
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80 # Puerto cambiado de 3000 a 80 PARA PROBAR CON NGINX
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: FRONTEND_URL
              value: "http://localhost:4200"
