apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasigo-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasigo-backend
  template:
    metadata:
      labels:
        app: wasigo-backend
    spec:
      containers:
        - name: wasigo-backend
          image: wasigodevacr.azurecr.io/wasigo-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "3000"
            - name: FRONTEND_URL
              value: "http://localhost:4200"
