apiVersion: apps/v1
kind: Deployment
metadata:
  name: wasigo-backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wasigo-backend
  template:
    metadata:
      labels:
        app: wasigo-backend
    spec:
      containers:
        - name: wasigo-backend
          image: wasigodevacr.azurecr.io/wasigo-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: wasigo-backend-config
            - secretRef:
                name: wasigo-backend-secret
