apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wasigo-backend
  namespace: backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - wasigo.20.241.197.34.nip.io
      secretName: wasigo-backend-tls
  rules:
    - host: wasigo.20.241.197.34.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wasigo-backend
                port:
                  number: 80
