apiVersion: v1
kind: Service
metadata:
  name: wasigo-backend
  namespace: backend
spec:
  selector:
    app: wasigo-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # debe coincidir con el containerPort del Deployment
  type: ClusterIP
