apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argocd-transport
  namespace: argocd
spec:
  insecureSkipVerify: true  # Esto quita el error 500 de Traefik al validar el certificado autofirmado de ArgoCD