apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: coraza-waf
  namespace: traefik
spec:
  plugin:
    coraza:
      directives: |
        SecRuleEngine On
        SecRequestBodyAccess On
        # Regla de prueba: Bloquea con un 403 si detecta la palabra 'hack'
        SecRule REQUEST_URI "@contains hack" "id:1,phase:1,deny,status:403,msg:'Bloqueado por WAF'"