apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: whitelist-segura
  namespace: traefik
spec:
  ipAllowList:
    sourceRange:
      - 127.0.0.1/32       # Acceso desde el propio cluster
      - 149.50.197.186/32  # Tu IP PÃºblica (Ecuador)